### ISSUE TITLE
access to shared mailboxes

### ISSUE THREAD

**Issue by dirks** [KrissN/akonadi-ews#13]
I could not yet figure out how to connect to shared mailboxes using the akonadi-ews agent. Is that implemented at the moment?

What I have tried:
- With IMAP I can provide domain\username\mailboxalias to connect a shared mailbox. Trying the same approach with the ews ressource gives me a 401 authentication error. The same if I do not specify the domain in the username but only in the domain field of the resource configurator.
- If I use my regular username but specify the mail address of the shared mailbox, it just adds my regular accounts mail folder.

**Comment by KrissN** [comment]
I am aware that Exchange/Outlook has such ability, but I have not yet made any effort to implement this. It is on the long TODO list though.

**Comment by KrissN** [comment]
Moved to KDE Phabricator: https://phabricator.kde.org/T7165
