### ISSUE TITLE
How to use this feature

### ISSUE THREAD

**Issue by mr-gosh** [KrissN/akonadi-ews#14]
If I have kde-neon - how can i use this feature? i cant't find any hint on this and the documentation and readme lacks a discription of this usage?!?

**Comment by cardonator** [comment]
Install the deb, install Kmail and KOrganizer, in Kmail settings add a new provider, select Microsoft Exchange, fill in credentials, profit immensely from having a half decent Exchange integration in Linux for once.

**Comment by floeschie** [comment]
I had to run `akonadictl restart` manually in a terminal before KOrganizer would show the Akonadi EWS provider.

**Comment by juri8** [comment]
I have kubuntu 17.04 and want to try this out. I managed building it from the sources, but is there a .deb available? If not, it's fine to go with the self-built code, but how can I make it show up in the akonadi plugins?

**Comment by KrissN** [comment]
The resource has been merged into KDE PIM and is expected to be released together with KDE Applications 17.12 in December. This means no more extra packages to install :)

**Comment by cardonator** [comment]
Hooray! Thanks!!
