### ISSUE TITLE
Does not show in kmail

### ISSUE THREAD

**Issue by megamaced** [KrissN/akonadi-ews#15]
Distro: openSUSE Leap 42.1
kdepim 15.12.3-18.5
Frameworks 5.21.0-12.1
QT  5.5.1

I built Akonadi-EWS  from git  today https://build.opensuse.org/package/show/home:megamaced/akonadi-ews

In KMail account settings, akonadi-ews is set up. Connects OK. Status shows Exchange 2013 OK. I can see the folder list in the Subscriptions tab.

However in the main KMail window I don't see any Exchange folders. I only have 'Local Folders' in the left hand side

**Comment by KrissN** [comment]
Can you try to hit "Check Mail" a few times? I have noticed that sometimes akonadi-ews fails to connect for the first time. I'm investigating why that could happen.

**Comment by bkchr** [comment]
That worked for me. I had to press the button a few times and also restarted Kmail.

**Comment by KrissN** [comment]
Yesterday I have added an improvement - based on the behaviour of other Akonadi resources, such as IMAP, the EWS resource will now sync the folder tree as soon as it connects to Exchange, so this should no longer happen.
