### ISSUE TITLE
Include packaging source

### ISSUE THREAD

**Issue by kolya-ay** [KrissN/akonadi-ews#17]
It would be cool to have sources for building `.deb`/`.rpm` packages in the repo. Among other things this would allow  to automate artifacts building with each release (Travis, etc).

**Comment by KrissN** [comment]
I have created and pushed a new repository - [akonadi-ews-packagespec](https://github.com/KrissN/akonadi-ews-packagespec) which contains the files needed to build the existing Fedora and Ubuntu packages. I'm not a packaging guru, so these probably have room for improvement (pull requests welcome).
