### ISSUE TITLE
Crash after resume from suspend to disk

### ISSUE THREAD

**Issue by kakra** [KrissN/akonadi-ews#18]
I just did "echo disk > /sys/power/state" and the system went to sleep. After resuming, akonadi-ews-resource crashed and dumped a lot of xml files to /tmp.

**Comment by kakra** [comment]
Probably ignore the dumps (I accidently left debug=true in qtlogging.xml). But it still crashed, probably because the connection has been interrupted by suspending the machine.

**Comment by KrissN** [comment]
This looks similar to an issue reported by a user over e-mail. In his case the mailbox was very large and during an initial sync the Exchange server started to return "Busy" at some point, which caused requests to fail and eventually the resource crashed.

I'm investigating why this is happening, but I admit that error recovery is not yet the strongest point of Akonadi EWS - I need to work on some more comprehensive testing.

**Comment by dhofstetter** [comment]
I have this kind of problem also! Is there some way how we can help to figure out the exact reason for this problem?

BR Daniel

**Comment by kakra** [comment]
Closing my own request, as it should be reported KDE upstream now. I'm currently not using suspend to disk due to other bugs so I have no way to test this.
