### ISSUE TITLE
Support Microsoft Exchange Proxy Settings (Outlook Anywhere)

### ISSUE THREAD

**Issue by divico** [KrissN/akonadi-ews#19]
Many Exchange server are not directly exposed to the internet. Instead of using a VPN, Outlook can connect to such servers via a proxy server using HTTP, this feature is called Outlook Anywhere my Microsoft. 

However, akonadi-ews in its current version does not allow to enter proxy settings. Is there any plan to implement proxy feature in akonadi-ews?

See [here](https://support.office.com/en-us/article/Use-Outlook-Anywhere-to-connect-to-your-Exchange-server-without-VPN-ae01c0d6-8587-4055-9bc9-bbd5ca15e817) for reference to this feature

**Comment by mozguletz** [comment]
In case if Outlook Web App is accessible from the Internet, you can use that URL.
For example, https://webmail.yourexchangeserver.com/owa to access Outlook Web interface, use https://webmail.yourexchangeserver.com/EWS/Exchange.asmx as EWS URL, this solution works for me.

**Comment by divico** [comment]
Thank you so much this is perfectly working with the Web App enabled.

Awesome work!
