### ISSUE TITLE
Failed to read POX response - unknown protocol 'EXHTTP'

### ISSUE THREAD

**Issue by Eig8phei** [KrissN/akonadi-ews#20]
While this worked just fine until yesterday, this morning the akonadi resource stays in offline mode even though sometimes is able to read folders and get new emails.

The autodiscover button show this message:

    Failed to read POX response - unknown protocol 'EXHTTP'

Starting akonadi-ews manually from the command line shows this:

<pre>
LANG=C /usr/bin/akonadi_ews_resource --identifier akonadi_ews_resource_0
Pass a valid window to KWallet::Wallet::openWallet().
Root folder is  EwsId(Top of Information Store, changeKey: AQAAABYAAAAA2S8yaDtQR6BZmWGLxhu4AABP63My)
log_ews_resource: Both tag lists in version 0 - not syncing
false
false
Root folder is  EwsId(Top of Information Store, changeKey: AQAAABYAAAAA2S8yaDtQR6BZmWGLxhu4AABP63My)
log_ews_resource: Both tag lists in version 0 - not syncing
false
log_ews_resource: Root collection fetched:  Collection ID: 15    remote ID: AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEIAAA=
   name: company
   url: QUrl(akonadi:?collection=15)
   parent: 0
   resource: akonadi_ews_resource_0
   rights: QFlags()
   contents mime type: (message/rfc822, inode/directory)
   isVirtual: false
    CachePolicy:
   inherit: true
   interval: -1
   timeout: -1
   sync on demand: false
   local parts: (ALL)
    CollectionStatistics:
   count: -1
   unread count: -1
   size: -1
false
false
log_ews_resource: Registering folder INBOX(39) as special collection 1
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAELAAA=(25) as special collection 2
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEJAAA=(19) as special collection 3
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEKAAA=(42) as special collection 4
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEPAAA=(41) as special collection 5
log_ews_resource: Failed to read EWS request - expected a child element in Folders element.
log_ews_resource: Failed to read EWS request - expected GetFolderResponse element.
log_ews_resource: Failed to read EWS request - expected GetFolderResponse element.
log_ews_resource: Both tag lists in version 0 - not syncing
log_ews_resource: Registering folder INBOX(39) as special collection 1
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAELAAA=(25) as special collection 2
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEJAAA=(19) as special collection 3
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEKAAA=(42) as special collection 4
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEPAAA=(41) as special collection 5
Root folder is  EwsId(Top of Information Store, changeKey: AQAAABYAAAAA2S8yaDtQR6BZmWGLxhu4AABP63My)
log_ews_resource: Both tag lists in version 0 - not syncing
false
log_ews_resource: Failed to read EWS request - expected a child element in Folders element.
log_ews_resource: Failed to read EWS request - expected GetFolderResponse element.
log_ews_resource: Failed to read EWS request - expected GetFolderResponse element.
log_ews_resource: Registering folder INBOX(39) as special collection 1
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAELAAA=(25) as special collection 2
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEJAAA=(19) as special collection 3
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEKAAA=(42) as special collection 4
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEPAAA=(41) as special collection 5
log_ews_resource: Both tag lists in version 0 - not syncing

retrieveItem
log_ews_resource: Failed to process EWS request: Timeout on server
owa.company.com: Socket operation timed out
ERROR "Failed to process EWS request: Timeout on server\nowa.company.com: Socket operation timed out"
log_ews_resource: Failed to process EWS request: Timeout on server
owa.company.com: Socket operation timed out
ERROR "Failed to process EWS request: Timeout on server\nowa.company.com: Socket operation timed out"
EwsMailHandler::setItemPayload
0 attachments
Root folder is  EwsId(Top of Information Store, changeKey: AQAAABYAAAAA2S8yaDtQR6BZmWGLxhu4AABP63My)
log_ews_resource: Both tag lists in version 0 - not syncing
false
false
false
log_ews_resource: Root collection fetched:  Collection ID: 15    remote ID: AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEIAAA=
   name: company
   url: QUrl(akonadi:?collection=15)
   parent: 0
   resource: akonadi_ews_resource_0
   rights: QFlags()
   contents mime type: (message/rfc822, inode/directory)
   isVirtual: false
    CachePolicy:
   inherit: true
   interval: -1
   timeout: -1
   sync on demand: false
   local parts: (ALL)
    CollectionStatistics:
   count: -1
   unread count: -1
   size: -1
log_ews_resource: Failed to read EWS request - expected a child element in Folders element.
log_ews_resource: Failed to read EWS request - expected GetFolderResponse element.
log_ews_resource: Failed to read EWS request - expected GetFolderResponse element.
log_ews_resource: Registering folder INBOX(39) as special collection 1
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAELAAA=(25) as special collection 2
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEJAAA=(19) as special collection 3
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEKAAA=(42) as special collection 4
log_ews_resource: Registering folder AAMkAGYyZTcyOTcxLWQxOWMtNDlkMC1hMjVjLWVhZTlmMTAwYTRhNAAuAAAAAADauHaq+CerQaw+i7eSZBr8AQAA2S8yaDtQR6BZmWGLxhu4AAAAAAEPAAA=(41) as special collection 5
log_ews_resource: Both tag lists in version 0 - not syncing
</pre>

If needed the debug log is at https://paste.kde.org/pd6ybrwo2/wt1baz (password akonadi).

Thanks

**Comment by cardonator** [comment]
Are you on Akonadi 16.12/5.4.0?

I just started getting this exact error...

**Comment by cardonator** [comment]
This seems to be related to this issue with Akonadi server 16.12 and Kmail 5.4.0.

https://forum.kde.org/viewtopic.php?f=309&t=137752&sid=024479c6c5a984e78ec1050e712f892c
https://bugs.kde.org/show_bug.cgi?id=373782

**Comment by Eig8phei** [comment]
Yes, I have the same versions too. I'll try re-adding the EWS account too.

**Comment by merlin-tc** [comment]
Not sure if it's related to the other bug.
I can't find any other error message like this: "log_ews_resource: Both tag lists in version 3 - not syncing" in non ews related problems.

When I delete my ews account from akonadi another imap account works just fine.
I already recreated my complete akonadi sql db and also recreated the ews account in akonadi to no avail.

**Comment by cardonator** [comment]
Yeah, I tried the resolution in that issue and it did nothing. That is on Neon User Edition which is what I'm using, though.

I did get rid of the POX message which happened every time I clicked Perform in the configuration screen.

What is the best way to clear out the PIM data for Akonadi and start from scratch? I don't have any account added except my Exchange account.

**Comment by jo-mei** [comment]
> What is the best way to clear out the PIM data for Akonadi and start from scratch? I don't have any account added except my Exchange account.

I always follow the instructions in the archlinux wiki: [https://wiki.archlinux.org/index.php/KDE#Clean_akonadi_configuration_to_fix_KMail](https://wiki.archlinux.org/index.php/KDE#Clean_akonadi_configuration_to_fix_KMail)

**Comment by KrissN** [comment]
Created KDE Phabricator task for autodiscovery improvements: https://phabricator.kde.org/T7176
