### ISSUE TITLE
Failed to read EWS request XML after upgrade to akonadi 16.12

### ISSUE THREAD

**Issue by hlavki** [KrissN/akonadi-ews#22]
Using endpoint https://owa.xxx.yy/EWS/Exchange.asmx
When I debug request/response, response is HTML. See attached [ews_xmldump_Ny24772.zip](https://github.com/KrissN/akonadi-ews/files/660544/ews_xmldump_Ny24772.zip)

Looks like authentication problem.

**Comment by KrissN** [comment]
It could be that authentication if forwarding to some SSO site. This should however not be the case for EWS requests.

Would it be possible to see the full log? You can send it to my private e-mail (krissn (at) op.pl) if you don't want to disclose potentially sensitive information.

**Comment by hlavki** [comment]
Finally it's not problem of akonadi-ews. Maybe some server issues, anyhow, now it works.

**Comment by hlavki** [comment]
Fixed with checked option **_Use custom User Agent_**.

**Comment by KrissN** [comment]
I knew it would come in handy one day :)

**Comment by cardonator** [comment]
I am having an odd problem that seems to be very similar to this but the Custom User Agent didn't entirely fix it.

Akonadi: 16.12
KMail: 5.4.0
akonadi-ews: 0.8.1

When I try to view an email, I get a "Retrieiving Folder Contents" screen that never goes away.

Occasionally, in the corner of the screen is an error saying "Unable to fetch item from backend (collection -1): Unable to retrieve item from resource: Did not receive a reply. Possible causes include... (a bunch of possible causes)".

Maybe importantly, the folders themselves seem to refresh and I can see new emails. However, when I click on one I get nothing. Looking at the akonadi console debugger, there doesn't seem to be any request to the resource when I try to access an email like I used to see. 

This seems like it started happening when I rebooted after upgrading to Akaonadi 16.12.

**Comment by giaso** [comment]
First of all, thanks for your great work!
Since 16.12 I am experienceing the exact symptoms as cardonator above. Custom Agent does not work and the messages are not retrieved, though the folders are syncing correctly. Is there anything I can do or provide you to help?

Thank you
G

**Comment by KrissN** [comment]
It's quite likely that your problems are different from what the OP was experiencing.

In any case if you'd like me to help please provide some logs. There is information in the README file on how to collect them. As usual if you're afraid of potentially disclosing sensitive information please send the logs to my private e-mail address (krissn (at) op.pl).

**Comment by hlavki** [comment]
In my case I started to log request/response messages and I realized that every response is HTML. So problem was probably in authentication. Information about logging is in [README.md](../blob/master/README.md). Anyway, the solution was a bit of a coincidence.

**Comment by cardonator** [comment]
@giaso It is very likely you are experiencing this issue: https://github.com/KrissN/akonadi-ews/issues/20 which the POX message is only coincidental to.
