### ISSUE TITLE
Build distro packages with OBS

### ISSUE THREAD

**Issue by cseader** [KrissN/akonadi-ews#27]
Kriss,
I love this project, and I am willing to help. It would greatly save time in your package building if your source was grabbed by build.opensuse.org. It has the ability to build packages for multiple distributions. Let me know if you would like me to help here.

-Cameron

**Comment by hlavki** [comment]
Hi,
[package for openSUSE](https://build.opensuse.org/package/show/home:hlavki/akonadi-ews) is already there.
