### ISSUE TITLE
Move to KDE infrastructure

### ISSUE THREAD

**Issue by ovidiub13** [KrissN/akonadi-ews#29]
Is it planned to move this project to the KDE infrastructure?

Since it's a (very) useful addition to the KDE PIM stack, I'd say it should be in the same place.

**Comment by Fredba** [comment]
Yes it would be a good idea !

**Comment by KrissN** [comment]
This is definitely the target at some point. I have tried to follow KDE coding standard rules to minimize the effort needed to get this accepted. However it is their call to decide about it. I have not asked for this to happen so far as I feel the resource needs some improvements and more complete functionality before it becomes a real value for the KDE PIM package.

**Comment by Fredba** [comment]
Great :+1:  keep up your good work !

**Comment by ovidiub13** [comment]
I think it can still be moved to a KDE repo, (mirrored here, as all KDE repos are), and not delivered with the KDEPIM, until it is done.

**Comment by KrissN** [comment]
This has been completed now and the resource is now part of KDE PIM. It is expected to be released together with KDE Applications 17.12.
