### ISSUE TITLE
URL rezolve not treated properly

### ISSUE THREAD

**Issue by ovidiub13** [KrissN/akonadi-ews#30]
The URL of the Exchange server that we use for setting up Evolution, does not work with this resource.

An error is thrown when I try to connect to the server:

```
ERROR "Failed to read EWS request XML"
```

Upon checking the received XML, I saw that it's actually the HTML page from the Outlook webmail login.

I've enabled debugging logs, and that's how I was able to examine the contents of that XML.

I don't know what other details I can and I'm allowed to provide in order to resolve this. Please ask for what you think might be useful, and I'll see what I can do.

**Comment by ovidiub13** [comment]
I've solved the issue. I was using the `<webmail URL>/OWA` and I was supposed to use the `<webmail URL>/ews/exchange.asmx`.

All is good. Thank you for your great work.

**Comment by ovidiub13** [comment]
I've talked with my coleagues, and I've come to actually consider this a bug. Evolution has a `Fetch URL` button that treats the `/OWA` URL and resolves the correct URL needed for the exchange server. 

The `Server Autodiscovery` doesn't seem to work in my case with the `/OWA` URL.

**Comment by KrissN** [comment]
Created KDE Phabricator task: https://phabricator.kde.org/T7176
