### ISSUE TITLE
Ews rW Calendar Support

### ISSUE THREAD

**Issue by F1nny** [KrissN/akonadi-ews#31]
Hey KrissN awesome job on this love it and thanks for your hard work! Just curious as to if there's been any progress on calendar 2way/write support? I'm sure we could open a bounty on it and it'd get a lot of attention! Just let me know how could start something like that if so!

**Comment by KrissN** [comment]
There is some progress, but it's slow due to lack of time and other high-priority things.

Please be patient.

**Comment by KrissN** [comment]
Created KDE Phabricator task: https://phabricator.kde.org/T7177
