### ISSUE TITLE
Plugin documentation

### ISSUE THREAD

**Issue by bastien-roucaries** [KrissN/akonadi-ews#33]
Sorry to use a bug report in order to contact.

It seems that you have implemented a kmailtransport plugin.

I plan to do the same in order to replace the deleted sendmail plugin for kmail.

Could you point me to documentation of how to implement ?

Thank you 

Bastien

**Comment by KrissN** [comment]
Hi,
I have used documentation on api.kde.org, more specifically the one related to the [TransportResourceBase](https://api.kde.org/kdepim/akonadi/html/classAkonadi_1_1TransportResourceBase.html) class. The documentation is not very extensive, but it is enough to get a feeling on how it's working.
