### ISSUE TITLE
new Version

### ISSUE THREAD

**Issue by dhofstetter** [KrissN/akonadi-ews#36]
Are their any plans to provide new versions periodically? 

Because e.g. for the expamle of arch user repositories there is still 0.8.1 as most recent. But since end of october 2016 there are a lot of commits! Are they not stable at the moment?

BR Daniel

**Comment by d-vogel** [comment]
Well you can still use https://aur.archlinux.org/packages/akonadi-ews-git

**Comment by dhofstetter** [comment]
Yes I just realized that afterwards, and changed to this package, thanks for your hint.

Hopefully the ews won't crash with every suspend.

Thanks anyway :) :+1:
