### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by benediktwinder** [KrissN/akonadi-ews#4]
I want to compile akonadi-ews on Archlinux but i got this error:

```
Scanning dependencies of target akonadi_ews_resource
[ 49%] Building CXX object CMakeFiles/akonadi_ews_resource.dir/calendar/ewscalendarhandler.cpp.o
In file included from /usr/include/KF5/AkonadiCore/exception.h:28:0,
                 from /usr/include/KF5/AkonadiCore/item.h:26,
                 from /usr/include/KF5/AkonadiCore/Item:1,
                 from /tmp/yaourt-tmp-bw/aur-akonadi-ews/src/akonadi-ews-0.8.0/ewsfetchitemdetailjob.h:25,
                 from /tmp/yaourt-tmp-bw/aur-akonadi-ews/src/akonadi-ews-0.8.0/calendar/ewsfetchcalendardetailjob.h:23,
                 from /tmp/yaourt-tmp-bw/aur-akonadi-ews/src/akonadi-ews-0.8.0/calendar/ewscalendarhandler.cpp:24:
/usr/include/KF5/AkonadiCore/std_exception.h:1:44: fatal error: /usr/include/c++/5.3.0/exception: No such file or directory
 #include "/usr/include/c++/5.3.0/exception"
                                            ^
compilation terminated.
CMakeFiles/akonadi_ews_resource.dir/build.make:105: recipe for target 'CMakeFiles/akonadi_ews_resource.dir/calendar/ewscalendarhandler.cpp.o' failed
make[2]: *** [CMakeFiles/akonadi_ews_resource.dir/calendar/ewscalendarhandler.cpp.o] Error 1
CMakeFiles/Makefile2:100: recipe for target 'CMakeFiles/akonadi_ews_resource.dir/all' failed
make[1]: *** [CMakeFiles/akonadi_ews_resource.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

I've installed all dependieces. Maybe i missed something? Maybe someone have an idea. Thanks a lot!

**Comment by KrissN** [comment]
I've checked the contents of `/usr/include/KF5/AkonadiCore/std_exception.h` on my system and it says:

```
#include "/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/include/g++-v5/exception"
```

I think this file is generated during compilation of Akonadi and fixed to the actual GCC-specific version of that file. Did you by any chance upgrade GCC to some other version or uninstall GCC 5.3.0 recently? It might be worth to install GCC 5.3.0 back or to rebuild the Akonadi package so that it pulls whatever GCC you have on your system.

**Comment by benediktwinder** [comment]
Thank you for the fast reply! I setup a new clean Archlinux machine and i have the same behavior. In a newly installed Archlinux i have GCC 6.1.1. I installed akonadi from the pacman packager. I will try to install GCC 5.3.0 or to compile Akonadi manuelly. If i have any news i will write it here. Thanks again for the quick reply.

**Comment by wienczny** [comment]
This is not a akonadi-ews problem. It's related to the Arch Linux update of GCC to 6.1.1 and should be fixed with the next build of the akonadi package using this compiler version.

**Comment by KrissN** [comment]
In such case I'll close the issue. Please reopen in case there are more problems.
