### ISSUE TITLE
autodiscovery failing

### ISSUE THREAD

**Issue by JR1994** [KrissN/akonadi-ews#41]
I running Debian Stretch trying to use akonadi-ews to pull my exchange mail. I installed using the ubuntu .deb package. I enter my credentials using the domain field to enter the domain and enter my username and password in the proper fields. It tries to autodiscover and fails. I tried disable the domain field and entered _username@domain_ for the username field and still fails.

**Comment by boospy** [comment]
Yes that did not work. Here on KDEneon the same. But a look at Startpageserach give you the answer:
`https://Hostname/EWS/Exchange.asmx`
But it is not useable for me, is see the mails, but i can't open one. (SBS2011)

**Comment by JR1994** [comment]
It is very frustrating Thunderbird works flawlessly with davmail

**Comment by KrissN** [comment]
Created KDE Phabricator task for autodiscovery improvements: https://phabricator.kde.org/T7176
