### ISSUE TITLE
Build / Installation instructions

### ISSUE THREAD

**Issue by al1en83** [KrissN/akonadi-ews#43]
Would be nice if you include installation instructions. More people would be able to test it an expose potential bugs. Regards

**Comment by boospy** [comment]
here some first info's https://github.com/KrissN/akonadi-ews/issues/40#issuecomment-315065056

**Comment by KrissN** [comment]
The EWS resource is now part of KDE PIM and is expected to be released with KDE Applications 17.12.

**Comment by boospy** [comment]
Nice :) have you a date when it goes NEON-Repo. Because i must remove my ews-package.
