### ISSUE TITLE
Cannot get data from EWS

### ISSUE THREAD

**Issue by ToeiRei** [KrissN/akonadi-ews#49]
Distro: Gentoo Linux
KDE Frameworks: 5.50.0
Qt 5.11.1
kde-apps/akonadi-18.08.1:5
EWS Connector: 5.9.1

Akonadi Console says:
Identifier: akonadi_ews_resource_2
Type: Microsoft Exchange Server (EWS)
Status: Online, Idle
Status Message: Ready
Capabilities: Resource, NeedsNetwork, X-EwsMailTransport
Mimetypes: text/directory, message/rfc822, text/calendar, application/x-vnd.kde.contactgroup, application/x-vnd.akonadi.calendar.event, application/x-vnd.akonadi.calendar.todo

Config seems to be okay, as I can see the folder structure in the 'Subscriptions' Tab of the (native) Config window.

Server Status:
Status: OK
Version: 14.3.123.3 (Exchange 2010 SP3)

**Comment by franjavifer** [comment]
I have the same problem. ¿How did you solved it?
